version: "3.8"

services:
  api:
    build:
      context: ./
      target: development
    volumes:
      - ./src:/application/src
    ports:
      - "8001:8001"
      - "8002:8002"
    command: npm run serve